# Generated by Django 5.2.6 on 2025-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_paciente_email_alter_paciente_telefone'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero',
            field=models.CharField(default=2, max_length=8),
            preserve_default=False,
        ),
    ]
