# Generated by Django 5.2.6 on 2025-11-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0004_paciente_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='numero',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
