# Generated by Django 5.2.6 on 2025-11-04 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0006_alter_paciente_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
