# Generated by Django 5.2.6 on 2025-11-04 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0007_consulta_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='desconto',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Desconto em %', max_digits=5),
        ),
        migrations.AddField(
            model_name='consulta',
            name='valor_final',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='dentista',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinic.dentista'),
        ),
        migrations.AlterField(
            model_name='consulta',
            name='procedimento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='clinic.procedimento'),
            preserve_default=False,
        ),
    ]
