# Generated by Django 5.2.6 on 2025-11-04 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0008_consulta_desconto_consulta_valor_final_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='comissao_valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dentista',
            name='comissao_percentual',
            field=models.DecimalField(decimal_places=2, default=40.0, help_text='Percentual de comissão (%)', max_digits=5),
        ),
    ]
