# Generated by Django 5.2.6 on 2025-11-10 17:43

import clinic.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0009_consulta_comissao_valor_dentista_comissao_percentual'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inicio_teste', models.DateTimeField(default=django.utils.timezone.now)),
                ('fim_teste', models.DateTimeField(default=clinic.models.default_fim_teste)),
                ('ativa', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
