# Generated by Django 5.2.6 on 2025-11-10 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0010_assinatura'),
    ]

    operations = [
        migrations.AddField(
            model_name='assinatura',
            name='tipo',
            field=models.CharField(choices=[('trial', 'Teste Gratuito'), ('basico', 'Plano Básico'), ('profissional', 'Plano Profissional'), ('premium', 'Plano Premium')], default='trial', max_length=20),
        ),
    ]
