# Generated by Django 5.2.6 on 2025-11-11 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0012_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamento',
            name='plnao',
            field=models.CharField(default='Indefinido', max_length=50),
        ),
    ]
