# Generated by Django 5.2.6 on 2025-11-11 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0013_pagamento_plnao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagamento',
            old_name='plnao',
            new_name='plano',
        ),
    ]
