# Generated by Django 5.2.6 on 2025-11-12 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0014_rename_plnao_pagamento_plano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedimento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='procedimento',
            name='valor_base',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
