# Generated by Django 5.2.6 on 2025-11-12 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0015_alter_procedimento_nome_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='valor_base',
            new_name='valor',
        ),
    ]
