# Generated by Django 5.2.6 on 2025-11-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0016_rename_valor_base_procedimento_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedimento',
            old_name='valor',
            new_name='valor_base',
        ),
    ]
