# Generated by Django 5.2.6 on 2025-11-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0017_rename_valor_procedimento_valor_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='data_pagamento',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='consulta',
            name='paga',
            field=models.BooleanField(default=False),
        ),
    ]
