# Generated by Django 5.2.6 on 2025-11-22 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0021_expense_income'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClinicaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_clinica', models.CharField(default='Minha Clínica', max_length=255)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos_clinicas/')),
                ('cor_primaria', models.CharField(blank=True, help_text='Ex: #0033ff', max_length=20, null=True)),
                ('cor_secundaria', models.CharField(blank=True, max_length=20, null=True)),
                ('rodape_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=255, null=True)),
                ('telefone', models.CharField(blank=True, max_length=50, null=True)),
                ('site', models.CharField(blank=True, max_length=120, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clinica_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
